// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_thermomether_png);    // assets/thermomether.png
LV_IMG_DECLARE(ui_img_forecast_icon_png);    // assets/Forecast_Icon.png
LV_IMG_DECLARE(ui_img_timer_icon_png);    // assets/Timer_Icon.png
LV_IMG_DECLARE(ui_img_sunicon_png);    // assets/SunIcon.png
LV_IMG_DECLARE(ui_img_cloudicon_png);    // assets/cloudIcon.png

// FONTS
LV_FONT_DECLARE(ui_font_monsterrat_64);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
