// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "Timer.h"

extern Timer myTimer;

void addMinute(lv_event_t * e)
{
	myTimer.addMnute();
}

void minusMinute(lv_event_t * e)
{
	myTimer.minusMinute();
}

void startTimer(lv_event_t * e)
{
	myTimer.startTimer();
}

void resetTimer(lv_event_t * e)
{
	myTimer.resetTimer();
}
