// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void addMinute(lv_event_t * e);
void minusMinute(lv_event_t * e);
void startTimer(lv_event_t * e);
void resetTimer(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
