// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_PanelMain;
extern lv_obj_t * ui_Line;
extern void ui_event_ButtonThermomether(lv_event_t * e);
extern lv_obj_t * ui_ButtonThermomether;
extern lv_obj_t * ui_ThermometherIcon;
extern void ui_event_ButtonForecast(lv_event_t * e);
extern lv_obj_t * ui_ButtonForecast;
extern lv_obj_t * ui_ForecastIcon;
extern lv_obj_t * ui_TimeLabel;
extern void ui_event_ButtonTimer(lv_event_t * e);
extern lv_obj_t * ui_ButtonTimer;
extern lv_obj_t * ui_TimerIcon;
extern lv_obj_t * ui_PanelTherm;
extern lv_obj_t * ui_PanelInternet;
extern lv_obj_t * ui_InternetTitle;
extern lv_obj_t * ui_LabelTemp;
extern lv_obj_t * ui_IntTempData;
extern lv_obj_t * ui_LabelHumidity;
extern lv_obj_t * ui_IntHumData;
extern lv_obj_t * ui_LabelWind;
extern lv_obj_t * ui_IntWindData;
extern void ui_event_Exit(lv_event_t * e);
extern lv_obj_t * ui_Exit;
extern lv_obj_t * ui_LabelExit;
extern lv_obj_t * ui_PanelHome;
extern lv_obj_t * ui_HomeTitle;
extern lv_obj_t * ui_LabelTempH;
extern lv_obj_t * ui_HomeTempData;
extern lv_obj_t * ui_LabelHumidityH;
extern lv_obj_t * ui_HomeHumData;
extern lv_obj_t * ui_PanelForecast;
extern lv_obj_t * ui_LabelHeader;
extern lv_obj_t * ui_PanelToday;
extern lv_obj_t * ui_LabelDay;
extern lv_obj_t * ui_TempDataToday;
extern lv_obj_t * ui_RainDataToday;
extern lv_obj_t * ui_TodaySunIcon;
extern lv_obj_t * ui_TodayCloudIcon;
extern lv_obj_t * ui_PanelTommorow;
extern lv_obj_t * ui_LabelDay1;
extern lv_obj_t * ui_TempDataTommrw;
extern lv_obj_t * ui_RainDataTommrw;
extern lv_obj_t * ui_TommrwSunIcon;
extern lv_obj_t * ui_TommrwCloudIcon;
extern lv_obj_t * ui_PanelDayAfter;
extern lv_obj_t * ui_LabelDay2;
extern lv_obj_t * ui_TempDataDayAfter;
extern lv_obj_t * ui_RainDataDayAfter;
extern lv_obj_t * ui_DayAfterSunIcon;
extern lv_obj_t * ui_DayAfterCloudIcon;
extern lv_obj_t * ui_PanelIn3Days;
extern lv_obj_t * ui_LabelDay3;
extern lv_obj_t * ui_TempDataIn3Days;
extern lv_obj_t * ui_RainDataIn3Days;
extern lv_obj_t * ui_In3DaysSunIcon;
extern lv_obj_t * ui_In3DaysCloudIcon;
extern void ui_event_ButtonExit(lv_event_t * e);
extern lv_obj_t * ui_ButtonExit;
extern lv_obj_t * ui_LabelExit1;
extern lv_obj_t * ui_PanelTimerPage;
extern lv_obj_t * ui_LabelHeader1;
extern lv_obj_t * ui_PanelTimer;
extern lv_obj_t * ui_LabelTimerData;
extern void ui_event_ButtonPlus(lv_event_t * e);
extern lv_obj_t * ui_ButtonPlus;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel2;
extern void ui_event_ButtonMinus(lv_event_t * e);
extern lv_obj_t * ui_ButtonMinus;
extern lv_obj_t * ui_Panel4;
extern void ui_event_ButtonStart(lv_event_t * e);
extern lv_obj_t * ui_ButtonStart;
extern lv_obj_t * ui_LabelStart;
extern void ui_event_ButtonReset(lv_event_t * e);
extern lv_obj_t * ui_ButtonReset;
extern lv_obj_t * ui_LabelReset;
extern void ui_event_ButtonExitTimer(lv_event_t * e);
extern lv_obj_t * ui_ButtonExitTimer;
extern lv_obj_t * ui_LabelExit2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_PanelMain;
extern lv_obj_t * uic_Line;
extern lv_obj_t * uic_ButtonThermomether;
extern lv_obj_t * uic_ThermometherIcon;
extern lv_obj_t * uic_ButtonForecast;
extern lv_obj_t * uic_ForecastIcon;
extern lv_obj_t * uic_TimeLabel;
extern lv_obj_t * uic_ButtonTimer;
extern lv_obj_t * uic_TimerIcon;
extern lv_obj_t * uic_PanelTherm;
extern lv_obj_t * uic_PanelInternet;
extern lv_obj_t * uic_InternetTitle;
extern lv_obj_t * uic_LabelTemp;
extern lv_obj_t * uic_TempIntDataLabel;
extern lv_obj_t * uic_LabelHumidity;
extern lv_obj_t * uic_IntHumData;
extern lv_obj_t * uic_LabelWind;
extern lv_obj_t * uic_IntWindData;
extern lv_obj_t * uic_Exit;
extern lv_obj_t * uic_LabelExit;
extern lv_obj_t * uic_PanelHome;
extern lv_obj_t * uic_HomeTitle;
extern lv_obj_t * uic_HomeTempData;
extern lv_obj_t * uic_HomeHumData;
extern lv_obj_t * uic_PanelForecast;
extern lv_obj_t * uic_LabelHeader;
extern lv_obj_t * uic_PanelToday;
extern lv_obj_t * uic_LabelDay;
extern lv_obj_t * uic_TempDataToday;
extern lv_obj_t * uic_RainDataToday;
extern lv_obj_t * uic_TodayCloudIcon;
extern lv_obj_t * uic_PanelTommorow;
extern lv_obj_t * uic_TempDataTommrw;
extern lv_obj_t * uic_RainDataTommrw;
extern lv_obj_t * uic_TommrwSunIcon;
extern lv_obj_t * uic_TommrwCloudIcon;
extern lv_obj_t * uic_PanelDayAfter;
extern lv_obj_t * uic_TempDataDayAfter;
extern lv_obj_t * uic_RainDataDayAfter;
extern lv_obj_t * uic_DayAfterSunIcon;
extern lv_obj_t * uic_DayAfterCloudIcon;
extern lv_obj_t * uic_PanelIn3Days;
extern lv_obj_t * uic_TempDataIn3Days;
extern lv_obj_t * uic_RainDataIn3Days;
extern lv_obj_t * uic_In3DaysSunIcon;
extern lv_obj_t * uic_In3DaysCloudIcon;
extern lv_obj_t * uic_ButtonExit;
extern lv_obj_t * uic_LabelExit1;
extern lv_obj_t * uic_PanelTimerPage;
extern lv_obj_t * uic_PanelTimer;
extern lv_obj_t * uic_LabelTimerData;
extern lv_obj_t * uic_ButtonPlus;
extern lv_obj_t * uic_ButtonMinus;
extern lv_obj_t * uic_ButtonStart;
extern lv_obj_t * uic_LabelStart;
extern lv_obj_t * uic_ButtonReset;
extern lv_obj_t * uic_LabelReset;
extern lv_obj_t * uic_ButtonExitTimer;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

