// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_PanelMain;
extern lv_obj_t * ui_TimeLabel;
extern lv_obj_t * ui_Line;
extern void ui_event_ThermometherButton(lv_event_t * e);
extern lv_obj_t * ui_ThermometherButton;
extern lv_obj_t * ui_ThermometherIcon;
extern lv_obj_t * ui_PanelTherm;
extern lv_obj_t * ui_PanelInternet;
extern lv_obj_t * ui_InternetTitle;
extern lv_obj_t * ui_LabelTemp;
extern lv_obj_t * ui_IntTempData;
extern lv_obj_t * ui_LabelHumidity;
extern lv_obj_t * ui_IntHumData;
extern lv_obj_t * ui_LabelWind;
extern lv_obj_t * ui_IntWindData;
extern void ui_event_Exit(lv_event_t * e);
extern lv_obj_t * ui_Exit;
extern lv_obj_t * ui_LabelExit;
extern lv_obj_t * ui_PanelHome;
extern lv_obj_t * ui_HomeTitle;
extern lv_obj_t * ui_LabelTempH;
extern lv_obj_t * ui_HomeTempData;
extern lv_obj_t * ui_LabelHumidityH;
extern lv_obj_t * ui_HomeHumData;
// CUSTOM VARIABLES
extern lv_obj_t * uic_PanelMain;
extern lv_obj_t * uic_TimeLabel;
extern lv_obj_t * uic_Line;
extern lv_obj_t * uic_ThermometherButton;
extern lv_obj_t * uic_ThermometherIcon;
extern lv_obj_t * uic_PanelTherm;
extern lv_obj_t * uic_PanelInternet;
extern lv_obj_t * uic_InternetTitle;
extern lv_obj_t * uic_LabelTemp;
extern lv_obj_t * uic_TempIntDataLabel;
extern lv_obj_t * uic_LabelHumidity;
extern lv_obj_t * uic_IntHumData;
extern lv_obj_t * uic_LabelWind;
extern lv_obj_t * uic_IntWindData;
extern lv_obj_t * uic_Exit;
extern lv_obj_t * uic_LabelExit;
extern lv_obj_t * uic_PanelHome;
extern lv_obj_t * uic_HomeTitle;
extern lv_obj_t * uic_HomeTempData;
extern lv_obj_t * uic_HomeHumData;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

