// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_HomeHumData;
lv_obj_t * uic_HomeTempData;
lv_obj_t * uic_HomeTitle;
lv_obj_t * uic_PanelHome;
lv_obj_t * uic_LabelExit;
lv_obj_t * uic_Exit;
lv_obj_t * uic_IntWindData;
lv_obj_t * uic_LabelWind;
lv_obj_t * uic_IntHumData;
lv_obj_t * uic_LabelHumidity;
lv_obj_t * uic_TempIntDataLabel;
lv_obj_t * uic_LabelTemp;
lv_obj_t * uic_InternetTitle;
lv_obj_t * uic_PanelInternet;
lv_obj_t * uic_PanelTherm;
lv_obj_t * uic_ThermometherIcon;
lv_obj_t * uic_ThermometherButton;
lv_obj_t * uic_Line;
lv_obj_t * uic_TimeLabel;
lv_obj_t * uic_PanelMain;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_PanelMain = NULL;
lv_obj_t * ui_TimeLabel = NULL;
lv_obj_t * ui_Line = NULL;
lv_obj_t * ui_ThermometherButton = NULL;
lv_obj_t * ui_ThermometherIcon = NULL;
lv_obj_t * ui_PanelTherm = NULL;
lv_obj_t * ui_PanelInternet = NULL;
lv_obj_t * ui_InternetTitle = NULL;
lv_obj_t * ui_LabelTemp = NULL;
lv_obj_t * ui_IntTempData = NULL;
lv_obj_t * ui_LabelHumidity = NULL;
lv_obj_t * ui_IntHumData = NULL;
lv_obj_t * ui_LabelWind = NULL;
lv_obj_t * ui_IntWindData = NULL;
lv_obj_t * ui_Exit = NULL;
lv_obj_t * ui_LabelExit = NULL;
lv_obj_t * ui_PanelHome = NULL;
lv_obj_t * ui_HomeTitle = NULL;
lv_obj_t * ui_LabelTempH = NULL;
lv_obj_t * ui_HomeTempData = NULL;
lv_obj_t * ui_LabelHumidityH = NULL;
lv_obj_t * ui_HomeHumData = NULL;
// event funtions
void ui_event_ThermometherButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PanelTherm, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_PanelMain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Exit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PanelMain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_PanelTherm, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelMain = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelMain, 480);
    lv_obj_set_height(ui_PanelMain, 320);
    lv_obj_set_align(ui_PanelMain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelMain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel = lv_label_create(ui_PanelMain);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel, 0);
    lv_obj_set_y(ui_TimeLabel, -100);
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel, "--:--");
    lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0x01BA11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TimeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Line = lv_obj_create(ui_PanelMain);
    lv_obj_set_width(ui_Line, 480);
    lv_obj_set_height(ui_Line, 3);
    lv_obj_set_x(ui_Line, 0);
    lv_obj_set_y(ui_Line, -60);
    lv_obj_set_align(ui_Line, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Line, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Line, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Line, lv_color_hex(0x01BA11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Line, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Line, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Line, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Line, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThermometherButton = lv_btn_create(ui_PanelMain);
    lv_obj_set_width(ui_ThermometherButton, 67);
    lv_obj_set_height(ui_ThermometherButton, 67);
    lv_obj_set_x(ui_ThermometherButton, -130);
    lv_obj_set_y(ui_ThermometherButton, 0);
    lv_obj_set_align(ui_ThermometherButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ThermometherButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ThermometherButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ThermometherButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThermometherButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ThermometherButton, lv_color_hex(0x01BA11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ThermometherButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ThermometherButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThermometherIcon = lv_img_create(ui_ThermometherButton);
    lv_img_set_src(ui_ThermometherIcon, &ui_img_thermomether_png);
    lv_obj_set_width(ui_ThermometherIcon, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_ThermometherIcon, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_align(ui_ThermometherIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ThermometherIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ThermometherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelTherm = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelTherm, 480);
    lv_obj_set_height(ui_PanelTherm, 320);
    lv_obj_set_align(ui_PanelTherm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelTherm, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelTherm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTherm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTherm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTherm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelInternet = lv_obj_create(ui_PanelTherm);
    lv_obj_set_width(ui_PanelInternet, 213);
    lv_obj_set_height(ui_PanelInternet, 150);
    lv_obj_set_x(ui_PanelInternet, -110);
    lv_obj_set_y(ui_PanelInternet, -60);
    lv_obj_set_align(ui_PanelInternet, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelInternet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelInternet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelInternet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelInternet, lv_color_hex(0x01BA11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelInternet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelInternet, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InternetTitle = lv_label_create(ui_PanelInternet);
    lv_obj_set_width(ui_InternetTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InternetTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InternetTitle, 0);
    lv_obj_set_y(ui_InternetTitle, -55);
    lv_obj_set_align(ui_InternetTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_InternetTitle, "OUTSIDE");
    lv_obj_set_style_text_color(ui_InternetTitle, lv_color_hex(0x01BA11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_InternetTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_InternetTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_InternetTitle, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTemp = lv_label_create(ui_PanelInternet);
    lv_obj_set_width(ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp, -35);
    lv_obj_set_y(ui_LabelTemp, -30);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemp, "Temperature:");
    lv_obj_set_style_text_color(ui_LabelTemp, lv_color_hex(0x01BA11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemp, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IntTempData = lv_label_create(ui_PanelInternet);
    lv_obj_set_width(ui_IntTempData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IntTempData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IntTempData, 70);
    lv_obj_set_y(ui_IntTempData, -30);
    lv_obj_set_align(ui_IntTempData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IntTempData, "--.-*C");
    lv_obj_set_style_text_color(ui_IntTempData, lv_color_hex(0x01BA11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IntTempData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IntTempData, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IntTempData, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHumidity = lv_label_create(ui_PanelInternet);
    lv_obj_set_width(ui_LabelHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumidity, -50);
    lv_obj_set_y(ui_LabelHumidity, -5);
    lv_obj_set_align(ui_LabelHumidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumidity, "Humidity:");
    lv_obj_set_style_text_color(ui_LabelHumidity, lv_color_hex(0x01BA11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelHumidity, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHumidity, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IntHumData = lv_label_create(ui_PanelInternet);
    lv_obj_set_width(ui_IntHumData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IntHumData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IntHumData, 68);
    lv_obj_set_y(ui_IntHumData, -5);
    lv_obj_set_align(ui_IntHumData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IntHumData, "--.-%");
    lv_obj_set_style_text_color(ui_IntHumData, lv_color_hex(0x01BA11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IntHumData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IntHumData, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IntHumData, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWind = lv_label_create(ui_PanelInternet);
    lv_obj_set_width(ui_LabelWind, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWind, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWind, -45);
    lv_obj_set_y(ui_LabelWind, 20);
    lv_obj_set_align(ui_LabelWind, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWind, "Wind (m/s)");
    lv_obj_set_style_text_color(ui_LabelWind, lv_color_hex(0x01BA11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelWind, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWind, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IntWindData = lv_label_create(ui_PanelInternet);
    lv_obj_set_width(ui_IntWindData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IntWindData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IntWindData, 58);
    lv_obj_set_y(ui_IntWindData, 20);
    lv_obj_set_align(ui_IntWindData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IntWindData, "-.- ");
    lv_obj_set_style_text_color(ui_IntWindData, lv_color_hex(0x01BA11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IntWindData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IntWindData, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IntWindData, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Exit = lv_btn_create(ui_PanelTherm);
    lv_obj_set_width(ui_Exit, 100);
    lv_obj_set_height(ui_Exit, 50);
    lv_obj_set_x(ui_Exit, 0);
    lv_obj_set_y(ui_Exit, 100);
    lv_obj_set_align(ui_Exit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Exit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Exit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Exit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Exit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Exit, lv_color_hex(0x01BA11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Exit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Exit, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Exit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Exit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelExit = lv_label_create(ui_Exit);
    lv_obj_set_width(ui_LabelExit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelExit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelExit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelExit, "Exit");
    lv_obj_set_style_text_color(ui_LabelExit, lv_color_hex(0x01BA11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelExit, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelHome = lv_obj_create(ui_PanelTherm);
    lv_obj_set_width(ui_PanelHome, 213);
    lv_obj_set_height(ui_PanelHome, 150);
    lv_obj_set_x(ui_PanelHome, 110);
    lv_obj_set_y(ui_PanelHome, -60);
    lv_obj_set_align(ui_PanelHome, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelHome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelHome, lv_color_hex(0x01BA11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelHome, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeTitle = lv_label_create(ui_PanelHome);
    lv_obj_set_width(ui_HomeTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeTitle, 0);
    lv_obj_set_y(ui_HomeTitle, -55);
    lv_obj_set_align(ui_HomeTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeTitle, "INSIDE");
    lv_obj_set_style_text_color(ui_HomeTitle, lv_color_hex(0x01BA11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeTitle, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTempH = lv_label_create(ui_PanelHome);
    lv_obj_set_width(ui_LabelTempH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempH, -30);
    lv_obj_set_y(ui_LabelTempH, -30);
    lv_obj_set_align(ui_LabelTempH, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTempH, "Temperature:");
    lv_obj_set_style_text_color(ui_LabelTempH, lv_color_hex(0x01BA11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTempH, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempH, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeTempData = lv_label_create(ui_PanelHome);
    lv_obj_set_width(ui_HomeTempData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeTempData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeTempData, 70);
    lv_obj_set_y(ui_HomeTempData, -30);
    lv_obj_set_align(ui_HomeTempData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeTempData, "--.-*C");
    lv_obj_set_style_text_color(ui_HomeTempData, lv_color_hex(0x01BA11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeTempData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeTempData, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeTempData, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHumidityH = lv_label_create(ui_PanelHome);
    lv_obj_set_width(ui_LabelHumidityH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumidityH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumidityH, -45);
    lv_obj_set_y(ui_LabelHumidityH, -5);
    lv_obj_set_align(ui_LabelHumidityH, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumidityH, "Humidity:");
    lv_obj_set_style_text_color(ui_LabelHumidityH, lv_color_hex(0x01BA11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHumidityH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelHumidityH, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHumidityH, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeHumData = lv_label_create(ui_PanelHome);
    lv_obj_set_width(ui_HomeHumData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeHumData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeHumData, 68);
    lv_obj_set_y(ui_HomeHumData, -5);
    lv_obj_set_align(ui_HomeHumData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeHumData, "--.-%");
    lv_obj_set_style_text_color(ui_HomeHumData, lv_color_hex(0x01BA11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeHumData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeHumData, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeHumData, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ThermometherButton, ui_event_ThermometherButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Exit, ui_event_Exit, LV_EVENT_ALL, NULL);
    uic_PanelMain = ui_PanelMain;
    uic_TimeLabel = ui_TimeLabel;
    uic_Line = ui_Line;
    uic_ThermometherButton = ui_ThermometherButton;
    uic_ThermometherIcon = ui_ThermometherIcon;
    uic_PanelTherm = ui_PanelTherm;
    uic_PanelInternet = ui_PanelInternet;
    uic_InternetTitle = ui_InternetTitle;
    uic_LabelTemp = ui_LabelTemp;
    uic_TempIntDataLabel = ui_IntTempData;
    uic_LabelHumidity = ui_LabelHumidity;
    uic_IntHumData = ui_IntHumData;
    uic_LabelWind = ui_LabelWind;
    uic_IntWindData = ui_IntWindData;
    uic_Exit = ui_Exit;
    uic_LabelExit = ui_LabelExit;
    uic_PanelHome = ui_PanelHome;
    uic_HomeTitle = ui_HomeTitle;
    uic_HomeTempData = ui_HomeTempData;
    uic_HomeHumData = ui_HomeHumData;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_PanelMain = NULL;
    ui_PanelMain = NULL;
    uic_TimeLabel = NULL;
    ui_TimeLabel = NULL;
    uic_Line = NULL;
    ui_Line = NULL;
    uic_ThermometherButton = NULL;
    ui_ThermometherButton = NULL;
    uic_ThermometherIcon = NULL;
    ui_ThermometherIcon = NULL;
    uic_PanelTherm = NULL;
    ui_PanelTherm = NULL;
    uic_PanelInternet = NULL;
    ui_PanelInternet = NULL;
    uic_InternetTitle = NULL;
    ui_InternetTitle = NULL;
    uic_LabelTemp = NULL;
    ui_LabelTemp = NULL;
    uic_TempIntDataLabel = NULL;
    ui_IntTempData = NULL;
    uic_LabelHumidity = NULL;
    ui_LabelHumidity = NULL;
    uic_IntHumData = NULL;
    ui_IntHumData = NULL;
    uic_LabelWind = NULL;
    ui_LabelWind = NULL;
    uic_IntWindData = NULL;
    ui_IntWindData = NULL;
    uic_Exit = NULL;
    ui_Exit = NULL;
    uic_LabelExit = NULL;
    ui_LabelExit = NULL;
    uic_PanelHome = NULL;
    ui_PanelHome = NULL;
    uic_HomeTitle = NULL;
    ui_HomeTitle = NULL;
    ui_LabelTempH = NULL;
    uic_HomeTempData = NULL;
    ui_HomeTempData = NULL;
    ui_LabelHumidityH = NULL;
    uic_HomeHumData = NULL;
    ui_HomeHumData = NULL;

}
